services:
  db:
    image: postgres:15-alpine
    container_name: go_cv_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gocv
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d gocv" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: go_cv_app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/gocv?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy